apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-ea45114e-9ab3-46e5-9c71-7df14e772086
  name: devfile-sample
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-94-tenant/load-app-ea45114e-9ab3-46e5-9c71-7df14e772086/devfile-sample@sha256:ce743a1cc91b9ea439ec24dfb8adb2c3a5c4284881c3244c70e21e8de6855ff0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
